require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/*'
    - 'config/initializers/*'
    - 'Gemfile'
Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude: ['guard', 'loop', 'describe']
  Max: 40
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/models/*'
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Metrics/MethodLength:
  Max: 60
Metrics/ModuleLength:
  Max: 150
Rails/FilePath:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/SymbolArray:
  Enabled: false

