name: Rails Tests

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.0'

    - name: Install dependencies
      run: bundle install

    - name: Build assets
      run: bundle exec rake assets:precompile

    - name: Set up database
      run: bundle exec rails db:setup

    - name: Run Rails tests
      run: bundle exec rails test

    - name: Fail if test errors
      run: |
        set -e
        bundle exec rails test
        result=$?
        if [ $result -ne 0 ]; then
          echo "::error::Rails test failures. Please fix them before merging."
          exit 1
        fi
